FFmpeg acc arm64
bepro-company/docker pull request #39
Opened 2023-06-14 16:35 UTC by jahwanoh

2023-06-14 16:43 UTC, bdwoo commented
Could you build a docker image with this PR and push to github package after merge?

2023-06-15 15:11 UTC, felibol requested changes

2023-06-15 15:11 UTC, felibol commented on stitching_base/ffmpeg.sh.arm64
> +wget https://github.com/jocover/jetson-ffmpeg/raw/master/ffmpeg_nvmpi.patch
Why is this from original repo but upper one from bepro? I think so better to use from bepro repo.

2023-06-15 17:02 UTC, felibol approved these changes

2023-06-23 09:41 UTC, merged